/*
this accompanies the EmailMainGUI and is instatiated in that main method
 */
package com.shivekyle.email;

/**
 *
 * @author shive
 */
public class LoginGUI extends javax.swing.JFrame {
    
   

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_name = new javax.swing.JTextField();
        user_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(310, 225));
        setMinimumSize(new java.awt.Dimension(310, 225));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(310, 225));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_name.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        user_name.setForeground(new java.awt.Color(85, 0, 0));
        user_name.setBorder(null);
        user_name.setCaretColor(new java.awt.Color(255, 255, 255));
        user_name.setOpaque(false);
        getContentPane().add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 190, 30));

        user_password.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        user_password.setBorder(null);
        user_password.setCaretColor(java.awt.Color.white);
        user_password.setOpaque(false);
        getContentPane().add(user_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kyleshive/images/Login_mail.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 230));

        setLocation(new java.awt.Point(650, 75));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JTextField user_name;
    public static javax.swing.JPasswordField user_password;
    // End of variables declaration//GEN-END:variables








}
